### ISSUE TITLE
Spawn Kneall Stronghold at the end of the round

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#103]
Change Kneall Stronghold to spawn at the end of the round instead of at random.

I believe this change will literally save the game. Here's why:
* We have at least two types of players right now:
    1. "Stronghold Farmers": their goal is to get into a Stronghold server and farm it for profit.
    2. "PvPers": their goal is to get into fights and to defend against sieges. Getting some real hardcore PvP action like it's 2016 is the main thing they want to do.
* By making the Stronghold spawn after the game gets to 1 team instead of instantly ending the round, we change the path for Stronghold Farmers to achieve their goals: they must now get the server into endgame and kill all but one team.
* The PvPers will attempt to prevent this, since they have fun by killing people and preventing them from successfully sieging. We inject fighting the PvPers into the critical path of the Stronghold Farmer game loop.
* This restores the overall game loop of the game and brings creating teams and sieging bases back into relevance. 
* By pitting the two classes of players against each other, we make the game fun for everyone!

**Comment by cswimr** [comment]
@GalaxyRoblox/devs @GalaxyRoblox/dev-advisors This is a good idea in my opinion, but if you haven't already given your opinion in the dev discord thread, you should probably comment here. This is a pretty substancial gameplay change, and we should try to iron out potential issues before implementing it.

**Comment by Wingysam** [comment]
You have like an hour before I have this in main btw I think

**Comment by Wingysam** [comment]
But that doesn't mean we can't change things after it ships!
