### ISSUE TITLE
Event Warning System

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#115]
Create a /server-warning \<message\> command that allows admins to place a warning banner at the top of the screen for everyone in the server until /warning is invoked again (with no arguments).

That way, admins could do something like
> /server-warning WARNING: ADMIN NPC EVENT IN PROGRESS -- USE YOUR SHIPS AT YOUR OWN RISK -- NO REFUNDS

**Comment by ButterDogg** [comment]
Maybe use this as an excuse to move :h to libadmin?

**Comment by Wingysam** [comment]
Yeah it can replace :h, I don't want to use the simple temporary banner thing we have now though.

**Comment by Wingysam** [comment]
![image](https://github.com/user-attachments/assets/623063c9-565d-4851-a066-fafed90a4332)
