### ISSUE TITLE
Commanding Presence throws errors on the client when the ship or base dies

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#118]
If the base dies or the Hyperion dies, the VFX breaks. The VFX should go away immediately when either dies, rather than just sitting there forever.

**Comment by cswimr** [comment]
Fixed in https://github.com/GalaxyRoblox/DevScripts/commit/91d79ecd6918ddee6ebeaa3ec25bb7321e1a56a2

**Comment by cswimr** [comment]
thanks github lmao, further improved in https://github.com/GalaxyRoblox/DevScripts/commit/e02a2c293f889b58885ddc1e3a34bec32d0910fa
