### ISSUE TITLE
Give player a message when attempting to launch AI fighters too close to friendly base

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#13]
Currently, when you try to launch AI fighters while you're too close to your base, it fails in a confusing way. I think it just literally does nothing? Instead, it should send a message in chat or in the AI fighter control panel that you're too close to \<starbase name\>.

**Comment by Wingysam** [comment]
Actually it looks like it already does?

![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/18403742/9944f220-7dc8-45e9-83d6-535cb3f4b363)

**Comment by Wingysam** [comment]
@GodrevyD what's the problem here?

**Comment by Revy404** [comment]
Okay not needed
