### ISSUE TITLE
Odyssey module cannot be turned off

### ISSUE THREAD

**Issue by LB078** [GalaxyRoblox/Issues-Public#130]
Odyssey module cannot be turned off

https://github.com/user-attachments/assets/91ac6663-7a63-43c8-bc0a-afbaa6f684a5

https://youtu.be/6TAiUWSoNOo

**Comment by LB078** [comment]
Ok so the original issue is fixed, however i've found one other issue.

the module effect isnt being played when toggled.

And the task.wait() is impacted by lag so switch to capturing the wait time and THEN update the fuel based on how long it actually took

**Comment by I-Am-Solaris** [comment]
of course the VFX doesn't work, David never bothered to make client-sided VFX for it. I'll adjust it to that. @LB078 Also, we could consider changing the coroutine and task.wait() to be a function connected to one of the RunService steps and use delta.

**Comment by I-Am-Solaris** [comment]
Module fix for both VFX and functionality is completed, the coroutine was migrated to the Heartbeat-connected function. Waiting for push

**Comment by I-Am-Solaris** [comment]
Any update on pushing this or if more needs to be done beforehand?

**Comment by I-Am-Solaris** [comment]
Module is completely finished, bug tested, and fixed in devscripts. Waiting on addition to main game.

**Comment by PataNautic** [comment]
This needs to be ported to main @Wingysam
