### ISSUE TITLE
Nimitz AI Fighters can get stuck in each other while deploying

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#19]
The Nimitz has AI fighters close together that spawn inside of each other sometimes when deploying. This is bad for performance and should be avoided. Add one or more HangarPoints to the Nimitz to fix the problem.

https://github.com/GalaxyRoblox/Issues-Public/assets/18403742/961d8489-408e-4f27-a6e3-ea4fd7553752

**Comment by PataNautic** [comment]
This has been fixed by changing the orientation of the offending fighters. Need a developer to push Nimitz (DEVS)☹ 



https://github.com/GalaxyRoblox/Issues-Public/assets/99784428/aba74308-d914-450b-8001-3cad35d4a846

**Comment by PataNautic** [comment]
@I-Am-Solaris If you'd like to port this yourself, you're free to do so

It gets rid of the perfect orientation Nimitz had going on, but it's a more elegant solution that moving all fighters to a HangarPoint

**Comment by PataNautic** [comment]
@Wingysam You can port this yourself if you'd like too-- Nimitz (DEVS) just needs to be pushed

**Comment by PataNautic** [comment]
Ignore above, this was pushed
