### ISSUE TITLE
Server Browser sometimes hangs

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#20]
In some cases, the server browser fails to send you into the game server. It leaves you stuck on a screen that looks like this:

![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/18403742/90723210-9417-44c0-bca6-f07dd1bd5f4d)

There is no loading text in the top left, so it must still be in the server browser side of the transition. It may be caused by Roblox's teleport calls hanging. There may be no fix for the issue other than just detecting it happening and shutting down the broken server.

One potential solution is to just make every server browser instance hold one player. That way every time you join the game you get a fresh server.

**Comment by Wingysam** [comment]
@GodrevyD can you try to reproduce this, and have me get in the server where the bug is happening so I can write a detection please?

**Comment by Wingysam** [comment]
Another case at https://discord.com/channels/204965774618656769/1252298080569528522

Potentially also https://discord.com/channels/204965774618656769/1253144643512700968

**Comment by Revy404** [comment]
Can't reproduce and rc said he contacted roblox over it, there hasn't been another case for a while
