### ISSUE TITLE
TextLabel in Mega Base wraps unintentionally

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#22]
![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/18403742/4180ecb1-dd7f-4b23-a8f9-37e403839c76)

This TextLabel is configured improperly. It's low-resolution and wraps when it should be slightly smaller or use TextScaled.

**Comment by I-Am-Solaris** [comment]
![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/115196996/db774623-794e-4762-8751-9c75decb6a90)

Increased resolution of text and removed text wrapping.
