### ISSUE TITLE
Move asymmetric turret on Phantom

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#26]
One of Phantom's turrets is on the side and it should probably be centered. Maybe it could go between the larger turrets since turrets can shoot through each other?

![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/18403742/dd107c38-8035-45ff-b622-a3f52a284184)

![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/18403742/b9c856f4-8035-4bf4-af58-1610a1b25cb0)

**Comment by I-Am-Solaris** [comment]
Turret has been moved to the centerline
