### ISSUE TITLE
Prevent U.N.E. from taking base ownership

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#31]
How exactly should this be implemented? Prevent them from damaging planets? Only from getting the last hit? Should it apply to bases that aren't planets, like Derelict Station or Freedom Base?

Also, take this scenario:
1. Kneall sieges Myriad
2. Myriad has territory and assimilates a player Starbase
3. That player Starbase is now owned by Kneall
4. U.N.E. players siege the Starbase

Should the U.N.E. players be able to 1. damage the Kneall Starbase and if so, 2. destroy it?

**Comment by PataNautic** [comment]
UNE should not be able to attack NPC bases entirely. UNE should also be unable to assimilate bases or planets

**Comment by Wingysam** [comment]
Should U.N.E. be able to attack AiTeam-owned bases that aren't owned by the NPC team? Like should U.N.E. be able to siege Kneall but not able to get the last hit?

**Comment by PataNautic** [comment]
I didn't consider that possibility since it is such a niche case. No final hit is perhaps the best way to go about it in that case.

If that is too complicated to add, then UNE abandoning claims they have outside of their main base would work as well (i.e. UNE captures Frion, they give up ownership of Frion after a couple minutes and Frion becomes neutral)

**Comment by Wingysam** [comment]
I mean the easiest thing we can do is just prevent U.N.E. from damaging bases in general

**Comment by PataNautic** [comment]
If they can't attack Kneall/pirate-owned bases, that's OK; it's a super niche situation anyways

**Comment by Wingysam** [comment]
Should "Peaceful" teams that aren't U.N.E. be able to damage bases? Or specifically U.N.E.? Like what if we add another peaceful team in the future?

**Comment by PataNautic** [comment]
I would futureproof and just add a **Peaceful** tag, but I think this may only ever be a problem unique to U.N.E.

**Comment by Wingysam** [comment]
The Peaceful tag already exists, my question was whether or not we should be using it or the team name specifically. So I'll use it

**Comment by Wingysam** [comment]
So we'll make it so that peaceful teams cannot damage bases or take ownership of them by assimilation.
