### ISSUE TITLE
Dialog Credits from/to MB

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#32]
The incrementCredits dialog action should transfer the credits from Mega Base. With negative values, this avoids pushing player credits into the void, and with positive values, it pulls them from MB instead of from thin air.

**Comment by cswimr** [comment]
Can this be a separate option in `incrementCredits`? It can default to True, but the behavior should be able to be disabled by devs on a per-action basis.

**Comment by Wingysam** [comment]
Yeah sure. I think disabling it might cause some accidental harm from devs but we can deal with that at the time.
