### ISSUE TITLE
Dire Wolf turrets are rotated improperly

### ISSUE THREAD

**Issue by PataNautic** [GalaxyRoblox/Issues-Public#42]
Self-explanatory 

![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/99784428/4cda559b-de84-4c89-aeb0-2ee7e5168df5)

**Comment by PataNautic** [comment]
Fixed, need a developer to push Dire Wolf (DEVS) 

![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/99784428/3e2a36dc-0995-45c4-b2a9-53f74a833165)

**Comment by I-Am-Solaris** [comment]
Will push momentarily

**Comment by I-Am-Solaris** [comment]
Change has been pushed to main
