### ISSUE TITLE
Adjust Mothership's docks

### ISSUE THREAD

**Issue by PataNautic** [GalaxyRoblox/Issues-Public#52]
The Mothership was designed in a period of Galaxy where the largest ships were as big as today's battleships. One single dread+ can take up both slots of each pair of docks, causing rampant docking issues.

Migrate (or entirely remove) Mothership's fighters, and move half of its exist docks to the opposite side of the ship.

![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/99784428/0976fde2-caf9-4409-a6b9-c538cafe3213)

**Comment by PataNautic** [comment]
This will take more work than I originally thought, resizing to L

**Comment by PataNautic** [comment]
This may end up rolling into a complete Mothership remodel, needs further discussion

**Comment by Revy404** [comment]
@PataNautic Raise this to me if you want to talk about it

**Comment by PataNautic** [comment]
I'm moving this into no iteration as I'm not entirely sure if I will be approach this in a reasonable amount of time /  how to approach it

**Comment by PataNautic** [comment]
Liam took on this task and it is done / in testing. W
