### ISSUE TITLE
Hailstorm Fighters can get stuck inside ship

### ISSUE THREAD

**Issue by PataNautic** [GalaxyRoblox/Issues-Public#56]
The awkward positioning of the fighters on the Hailstorm can cause them to easily get stuck, potentially flinging the ship and causing immense lag to the server. 

Adjust the spots of the Frostfires and/or add a HangarPoint to prevent this from occurring. Making the fighters easily player-accessible is preferable, but not required.

![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/99784428/10cdc2fc-a0c5-4423-b3a4-998da01611d0)

**Comment by PataNautic** [comment]
![Image](https://github.com/GalaxyRoblox/Issues-Public/assets/99784428/e68b29a0-4b38-4077-ad8c-722157f08219)

This should no longer be an issue, ready to go (Hailstorm (DEVS)). The fighter positioning isn't as elegant as I'd like it to be, but I think this is a better solution than just putting a HangarPoint on it.

**Comment by cswimr** [comment]
Pushed to main in [`48e5b44`](https://github.com/GalaxyRoblox/Assets/commit/48e5b44b0c2cd10510c402a35552518cd891dc74)
