### ISSUE TITLE
Make AIs not spawn on top of people

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#6]
When an AI spawns, make it spawn offmap then warp in so it doesn't just spawn on someone and instantly kill them.

**Comment by PataNautic** [comment]
Do you think this behavior can be manually enabled when spawning npcs through command, perhaps a bool `warpIn`?

Will this also be compatible for excursion events where NPCs spawn around a base as opposed to a random point on the map?

**Comment by Wingysam** [comment]
It doesn't apply to NPCs that were given a point to spawn near, no. I don't see any situation where we want NPCs to spawn in a random region of space though. Is there any reason to implement the option to have them spawn potentially on top of people? 

To intentionally spawn on someone I understand, and that's already a thing.

**Comment by PataNautic** [comment]
You're right; manually toggling the behavior is pretty redundant, though I thought it may be cool for Admins to have control of for more dramatic NPC spawns

So if I am understanding correctly, NPCs that spawn around a designated area (I.E. Kneall ships spawning around the Stronghold) do not warp in? If this is the case, can this behavior be considered for NPCs that spawn this way too? I think it would add a lot of visual flair for an armada of Kneall to warp in to protect the Stronghold

**Comment by Wingysam** [comment]
If you don't want them to spawn near the Stronghold, can't you just unset the spawnposition? Or you want them to spawn on the point of the edge of the map closest to stronghold with some small randomization?

**Comment by PataNautic** [comment]
That's what I'm implying: have a bit of randomization in their spawns, and have them warp in to aid the Stronghold as opposed to spawning right next to it

This is a low priority though and having random spawns already have this mechanic is good enough in my eyes

**Comment by Wingysam** [comment]
Oh like spawn in a circle around the Stronghold?

**Comment by PataNautic** [comment]
That could work too. Where they end up doesn't really matter besides still being around a base (I.E. Stronghold), what matters to me is them warping into the map to a designated target when they spawn, as opposed to spawning in right on said target

**Comment by Wingysam** [comment]
Ohh like you want them to warp to their RoamPosition, even if they have NoWarp true?

**Comment by PataNautic** [comment]
Yeah, if RoamPosition designates where they first spawn

**Comment by Wingysam** [comment]
That's SpawnPosition. RoamPosition is where they fly to and then sit around waiting for targets when they don't have tasking.
