### ISSUE TITLE
Annihilator brawler teleporter puts you in a wall

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#79]
The teleporter to go to the A - Brawler in the Annihilator leaves you inside of a wall in the A - Brawler. The teleporter receiver needs to be moved slightly to reflect where the interior of the A - Brawler actually is.

[Discord bug report](https://discord.com/channels/204965774618656769/1262051257015599214)

**Comment by PataNautic** [comment]
Increasing to S, this appears to be an issue because A-Brawler does not have collisions set up period, nor does it have a proper interior.

**Comment by Liamglxy** [comment]
I have fixed this issue, awaiting push to main

**Comment by PataNautic** [comment]
Pushed
