### ISSUE TITLE
Create rename-team command

### ISSUE THREAD

**Issue by Wingysam** [GalaxyRoblox/Issues-Public#88]
Allow admins to reset a team's name to a random (same set as Xbox/chatbanned) name in case of bypasses. This will allow them to eliminate team names that aren't appropriate for Roblox without disrupting gameplay.

**Comment by Jaxumi92** [comment]
Could you also add the ability for admins to rename the faction entirely to a different name if the current faction leader requests it? (ie the faction leader isn't sure if its legal or not, and we're not too sure, we just rename it to something he requests)

**Comment by Wingysam** [comment]
Yeah I don't see why it can't take a new name parameter.

**Comment by I-Am-Solaris** [comment]
wouldn't a better command be /rename-team then and by default it uses a random name?

**Comment by Wingysam** [comment]
Yeah it's called rename-team in dev
