### ISSUE TITLE
Randomly select a loading screen image from a list of images in `LoadingScreenImage`

### ISSUE THREAD

**Issue by cswimr** [GalaxyRoblox/Issues-Public#91]
ViklyMF has provided us with some excellent art, and I'd like to use some of it for loading screen art.

**Comment by cswimr** [comment]
It is not currently possible to set multiple loading screen images in EventConfig as far as I can tell. The current IntValue `LoadingScreenImage` could be made a csv-formatted `StringValue` instead. I'm assigning @GodrevyD to this issue instead of myself until this is possible.

**Comment by Wingysam** [comment]
@GodrevyD the code for assigning the loading screen image is in Core/src/ServerScriptService/GameScript. You have all of the required permissions to do this and ship it to main
